### ISSUE TITLE
libGL error: failed to load driver: swrast

### ISSUE THREAD

**Issue by gnzlbg** [XQuartz/quartz-wm#11]
I'm getting:

> libGL error: failed to load driver: swrast

when trying to open an application via ssh -Y.  When using `ssh -x` I get:

> QXcbConnection: Could not connect to display 

No idea how to proceed or what information you might need.

**Comment by righthalfplane** [comment]
The problem go away - if you down grade to XQuartz 2.7.8 - it would be nice if somebody fixed the problem in newer versions

**Comment by jeremyhu** [comment]
This is not a quartz-wm issue.  Please file an issue againsg mesa or in the general XQuartz bug tracker if this is still an issue with 2.8.0_alpha1 or later.
