### ISSUE TITLE
Color issue when using Wine

### ISSUE THREAD

**Issue by oivindbj** [XQuartz/quartz-wm#13]
I am not 100% sure if this is truly an issue with XQuartz, but i suspect it is. Thats why I'm posting here.

Wine ([winehq.org](https://winehq.org)) is a software for running Windows applications on Linux or macOS.
The mac version depends on XQuartz.

I installed Wine on my mac ( 10.12.6 Sierra ) for the purpose of running DisplayMate for Windows ([displaymate.com](http://displaymate.com))

DisplayMate is a software that displays test patterns for testing or calibrating displays.

**Here is the problem:**
It quickly became obvious that the RGB numbers that DisplayMate claimed to output was NOT what was sent to the screen. I confirmed this using the Digital Color Meter in macOS (Utilities folder).

I also tested DisplayMate in Wine for Linux (Ubuntu), and there were no problems.

I suspect that XQuartz assigns an ICC profile for everything it draws to the screen. Or maybe Wine does.
In either case the active color management in macOS (ColorSync) respects this profile and converts the colors to the profile set for the display in System Preferences.

Since DisplayMate (and I believe most Windows GUI Software) is not associated with an ICC Profile (aka. unmanaged), assigning one is incorrect, and makes DisplayMate useless in Wine on the mac.

**Expected behaviour:**
Again, I am not sure if the issue is with XQuartz or Wine, but anyways.
Content that has an ICC profile associated with it (like many images) should of course be respected, and ColorSync should convert those.

BUT, for unmanaged content the numbers should pass by ColorSync untouched.

**Comment by oivindbj** [comment]
**UPDATE**

I have found what profile is being incorrectly assigned.
It is the "Generic RGB Profile.icc"

I confirmed this by setting "Generic RGB Profile.icc" as my display profile, and using the Digital Color Meter (Utilities folder) to measure the RGB values of DisplayMate.

I now get exactly the same numbers from the color meter as DisplayMate claims to output.

Whether the bug is in XQuartz or Wine, the solution should be to stop assigning "Generic RGB Profile.icc" to the content rendered.

**Comment by KenThomases** [comment]
Are you sure you're using Wine's X11 driver? By default on macOS, it will use the Mac driver, which doesn't involve X11, XQuartz, or quartz-wm. If you're actually using the Mac driver, I believe I know what's wrong and it's a bug in Wine.

**Comment by oivindbj** [comment]
Thank you for the information!
No, XQuartz does not launch when I use DisplayMate in Wine. It is never the active app.
So, like you say. That means I'm using the Mac driver.

Thanks for submitting the patch!

**Comment by KenThomases** [comment]
You're welcome. Thanks for reminding me of the issue. Closing this issue as unrelated to XQuartz or quartz-wm.
