### ISSUE TITLE
Window spans multiple monitors

### ISSUE THREAD

**Issue by Alex-Mann** [XQuartz/quartz-wm#14]
When opening a window from the command line the window spans multiple monitors. I'm assuming this has not been optimized for retina display's and that the monitor mismatch (retina display vs regular display) is causing this issue somewhere. If anyone has any ideas where to start to look at this code, I can probably submit a fix.

Thanks.

**Comment by KenThomases** [comment]
With what client program? (For example, `xterm` doesn't do that here.)

Unless the mode is altered by XRandR, the X server presents the whole desktop as a single screen. Your client program is probably just trying to center the window on that screen.

**Comment by Alex-Mann** [comment]
I'm using a hardware design program, called Simvision. It makes sense that it is trying to center in the middle of the screen since it always shows up on my middle monitor.

Are there any changes I can make to constrict how large this window opens as?

As another comment, I use a program called Magnet to easily split and fullscreen windows on my mac.. XQuartz windows don't respond to this program (almost like the title bar doesn't get recognized when hitting a screen edge). Any ideas here?

**Comment by jeremyhu** [comment]
Yeah, apps are allowed to open windows at whatever size they want.  You probably need to contact the vendor of that software to make it multi-monitor aware.
