### ISSUE TITLE
Applications -> Customize becomes unusable

### ISSUE THREAD

**Issue by yesyves** [XQuartz/quartz-wm#17]
Hi

I'm using current Macports X11 (xorg-server 1.20.10 / quartz-wm 1.3.2) on BigSur (11.1) and the Customize Applications list window always work on X11 startup but becomes unusable after a while : 

- The blue line over selected items becomes black and opaque
- Selecting another item does not work
- Double-clicking an item makes the texte become invisible although it is still possible to write in it

I would love to have reproducible steps to give you, especially that it now seems to be running very fine today ! The one thing that may have changed is that I removed default Xlogo and Xman from the menu ...

Thanks !

**Comment by yesyves** [comment]
I found how to reproduce it ! Just turn on Dark Mode and thing go bad. 

The following screenshots all actually contain the same data.

<img width="1032" alt="Capture d’écran, le 2021-01-18 à 00 00 59" src="https://user-images.githubusercontent.com/5402389/104874228-68fa6d00-5920-11eb-9d25-6af5ec67f8aa.png">
<img width="1034" alt="Capture d’écran, le 2021-01-18 à 00 01 10" src="https://user-images.githubusercontent.com/5402389/104874230-69930380-5920-11eb-8d0a-6efa925940f3.png">
<img width="855" alt="Capture d’écran, le 2021-01-18 à 00 01 39" src="https://user-images.githubusercontent.com/5402389/104874231-69930380-5920-11eb-9f38-c2471965c13c.png">

**Comment by jeremyhu** [comment]
This repo is for quartz-wm.  The issue you are reporting is about XQuartz.app.  Please reprot this issue at https://github.com/XQuartz/XQuartz/issues or https://gitlab.freedesktop.org/xorg/xserver/-/issues

I'm actually going to close this repo because quartz-wm is now part of the freedesktop.org gitlab instance.
