### ISSUE TITLE
X11 forwarding request failed on channel 0

### ISSUE THREAD

**Issue by psiqueira** [XQuartz/quartz-wm#8]
I am trying to do X11 forwarding through XQuartz on my iMac running OX X El Capitan (10.11.6).

when I try to use ssh with port forwarding, I get the error that the port forwarding request has failed.

that is, when I type: 

    ` ssh -Y xxx@computer.edu`

it comes back with 

`X11 forwarding request failed on channel`

when I try this same thing from another macintosh running OS X to the same destination computer, I do not get this error.

Does anyone have a suggest at how to find out what the problem is?

Thank you, Paul

**Comment by jeremyhu** [comment]
This is not a mailing list.  You should ask for help on xorg@lists.freedesktop.org or x11-users@lists.apple.com for such questions about X11, or maybe an OpenSSH mailing list.

If you search google for this error string, there are tons of hits.  Eg:

http://ask.xmodulo.com/fix-broken-x11-forwarding-ssh.html

One common case is a misconfigured XauthLocation in the server's sshd_config
